### ISSUE TITLE
自动同步上游的频率是否有点过高

### ISSUE THREAD

**Issue by Tsuk1ko** [y1ndan/genshin-impact-helper#39]
我觉得直接把同步写到每日签到之前就可以了，毕竟只有这时候才真正运行了代码，而且这样手动执行的时候也会自动同步

虽然 GitHub Actions 不要钱但节制一点总归是好的（x

**Comment by y1ndan** [comment]
有道理

**Comment by Tsuk1ko** [comment]
其实我指的是这样，`sync.yml` 不要了，合并到 `main.yml` 里

```yaml
# main.yml
name: "Genshin Impact Helper"

on:
  schedule:
    - cron: "0 22 * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Fork sync
        uses: tgymnich/fork-sync@v1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: y1ndan
          base: master
          head: master

  build:
    runs-on: ubuntu-latest
    needs: sync # run after sync

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
         ref: master

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run sign
        run: |
          pip install -r requirements.txt
          echo "${{ secrets.COOKIE }}" | tr '#' "\n" | xargs -I {} sh -c 'echo "{}" | python3 ./genshin.py'
```

**Comment by y1ndan** [comment]
之前就是合在一个.yml，后来发现fork有可能失败 但是签到在机制不变的前提下不会失败，所以拆成两个.yml

**Comment by Tsuk1ko** [comment]
也许可以使用 [`if: ${{ always() }}`](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#always)

[关于 needs](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds)

> Identifies any jobs that must complete successfully before this job will run. It can be a string or array of strings. If a job fails, all jobs that need it are skipped **unless the jobs use a conditional statement that causes the job to continue**.

当然要是实在不想折腾就算了😂

**Comment by Celeter** [comment]
直接从[y1ndan/genshin-impact-helper](https://github.com/y1ndan/genshin-impact-helper)拉取就行了，这样就不会有合并失败的问题了
```
name: "Genshin Impact Helper"

on:
  schedule:
    - cron: "0 22 * * *"  # scheduled at 06:00 (UTC+8) everyday

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          repository: y1ndan/genshin-impact-helper
          ref: master

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run sign
        run: |
          pip install -r requirements.txt
          echo "${{ secrets.COOKIE }}" | tr '#' "\n" | xargs -I {} sh -c 'echo "{}" | python3 ./genshin.py'
```
